---
# tasks file for mysql_db
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade the OS (apt-get dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist

- name: Install MySQL database
  apt:
    pkg:
      - mysql-server
      - mysql-client

- name: Install multi python packages for database
  ansible.builtin.pip:
    name:
      - PyMySQL

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Removes all anonymous user accounts
  community.mysql.mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Removes anonymous user account for localhost
  community.mysql.mysql_user:
    name: ''
    host: localhost
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create Database with name
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create Database user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
    login_unix_socket: /run/mysqld/mysqld.sock
